language: cpp
compiler:
    - gcc

os:
    - linux
    - osx

# use containers
sudo: false

env:
  - TYPE=Release DEVSPACE=$TRAVIS_BUILD_DIR/..

script:
  - git clone --depth 1 git://git.dcmtk.org/dcmtk.git dcmtksrc
  - cd dcmtksrc && mkdir -p build-$TYPE && cd build-$TYPE
  - cmake .. -DDCMTK_WITH_TIFF=OFF -DDCMTK_WITH_PNG=OFF -DDCMTK_WITH_OPENSSL=OFF -DDCMTK_WITH_XML=OFF -DDCMTK_WITH_ZLIB=ON -DDCMTK_WITH_SNDFILE=OFF -DDCMTK_WITH_ICONV=OFF -DDCMTK_WITH_WRAP=OFF -DCMAKE_INSTALL_PREFIX=$DEVSPACE/dcmtk/$TYPE
  - make -j8 install
before_deploy:
  - cd $TRAVIS_BUILD_DIR/..
  - zip -r latest.zip dcmtk/$TYPE
  - mkdir -p dpl_cd_upload
  - mv latest.zip $TRAVIS_BUILD_DIR/../dpl_cd_upload/dcmtk-$TRAVIS_OS_NAME.zip
deploy:
  provider: s3
  access_key_id: AKIAJLIJS2MGONMUBW4A
  secret_access_key:
    secure: "fEly021MvCGHu5leV5Mv+oneG8K5MDsCdhJAasdDEL7EhiElMNGRYeZdF9I4VuWmsY1TEa8sA/UwOvvJMXZ8/lJBGbfBKivU+wZX4EWOcCi3zkHLoayesSanubKpkqM651UTHHEx315OZytfYhA4AolnpC4SCUEG2hTcUf8PjJ0SWcXxK4eKGy8lhyEh70Vn6LpCNoltjBV/a/3CYaUXeGSqh8mkgEdaCOhisG817qhx5Xp/gOLF5+jGyy16fKLGl2oMc8z5vrvnmuZLxKNKeXIZkqooWqS2sJ4sxoSk4MdF7WYOIUDoBwbyCSkO65FbnmPBPJQFe5q8QpNLTY6IodYNiYjZV2+Bj9O80eBH5MfJqR1ki2LRBk2wTaWm6s5DpCkGRp3uB573HxFrTf12A4w4hmilrsDwbESQCsRqcy6vLBinFpNgnNBQyZ7umzIjeiXfi8+PslyOf75iQIrSPusjQhns1Z37t1hrw/I42nYiYfsBnkZS9RkKvSMe6LUT1O8lc5EgLbewlO5Zigsi2dcp1z+H1gR1o6EFgNETs6H8JOmBWPlLpGBsknL/o5hPbY3YsHMcFs/VN3kTYsfb1iQf/e6dV2CTgse6LEFoLilUD+LGx0ouA3BTy8nqLbT/hzDWtXkx77lYo5AlXTJWfJCEBJz7uo2TsNtrR9UGUkM="
  bucket: draconpern-buildcache
  acl: public_read
  skip_cleanup: true
  local_dir: dpl_cd_upload
